swagger: '2.0'
info:
  version: 0.0.1
  title: CoinArrival-Serverend
  description: Serverend API conrtains of CoinArrival.
schemes: 
- http
host: localhost
paths:
  /public/*:
    get:
      description: Get public assests
      produces: 
        - anything/*
      responses:
        200:
          description: Resource successfully shipped
        404:
          description: Resource not found
  /check_pass:
    post:
      description: Login check
      consumes: 
        - application/json
      parameters: 
        - in: body
          name: account
          description: Account to be verify
          schema:
            type: object
            required: 
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: Successfully login
        406:
          description: No such username or unmatched password
  /account:
    get:
      description: Get personal infomation of an account   
      parameters: 
        - in: query
          name: username
          type: string
      produces: 
        - application/json
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              username:
                type: string
              email:
                type: string
              phone:
                type: string
              avatar:
                type: string
        404:
          description: User not found
        401:
          description: Requested before login
        
    post:
      description: Create an account with given info or login
      consumes: 
        - application/json
      parameters: 
        - in: body
          name: account
          description: Username and password of account
          schema:
            type: object
            required: 
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        201:
          description: Successfully created
        400:
          description: Invalid info format
        409:
          description: Confict username
    put:
      description: Update account info
      consumes: 
        - application/json
      parameters: 
        - in: body
          name: account
          description: The account info to be updated
          schema:
            type: object
            required: 
              - username
            properties:
              username:
                type: string
              password:
                type: string
              email:
                type: string
              phone:
                type: string
              avatar:
                type: string
      responses:
        201:
          description: Successfully updated
        401:
          description: Requested before login as the edited account